<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Carbon\Carbon;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            'External Hard Drive',
            'Camera',
            'SSD',
            'RAM',
            'Graphics Card',
            'Motherboard',
            'Pen Drive',
            'Keyboard',
            'Mouse',
            'Monitor & Display'
        ];

        foreach ($products as $product) {
            DB::table('product_names')->insert([
                'name' => $product,
                'created_by' => 1,
                'modified_by' => 1,
                'is_deleted' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }


        for ($i = 1; $i <= 25; $i++) {
            $product = $products[array_rand($products)];
            $purchaseDate = Carbon::now()->subDays(rand(10, 365));
            $expiryDate = (clone $purchaseDate)->addYear();
            DB::table('warranty_records')->insert([
                'user_name' => 'User ' . $i,
                'mobile_number' => '98765' . rand(10000, 99999),
                'email' => "user{$i}@example.com",
                'purchase_source' => 'Online Store',
                'address' => '123 Street, City, State',
                'product_name' => $product,
                'serial_number' => strtoupper(Str::random(10)),
                'purchase_date' => $purchaseDate->toDateString(),
                'expiry_date' => $expiryDate->toDateString(),
                'warranty_status' => ['Pending', 'Active', 'Expired', 'Rejected'][rand(0, 3)],
                'is_deleted' => 0,
                'modified_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }



        DB::table('general_settings')->insert([
            'id' => 1,
            'brand_logo' => 'uploads/general_settings/general_setting_kingster-logo.png',
            'brand_white_logo' => 'uploads/general_settings/general_setting_kingster-white-logo.png',
            'brand_fevicon' => 'uploads/general_settings/general_setting_fevicon-icon.png',
            'header_banner_1' => 'uploads/general_settings/general_setting_banner1.jpg',
            'header_banner_2' => 'uploads/general_settings/general_setting_banner2.jpg',
            'header_banner_3' => 'uploads/general_settings/general_setting_banner3.jpg',
            'header_banner_4' => null,
            'customer_support_mobile' => '1800 890 5576',
            'customer_support_email' => 'support@kingster.info',
            'office_time' => 'Mon–Sat, 10 AM–6 PM',
            'footer_about_us_1' => 'Kingster is one of India’s fastest-growing tech brands, known for top-selling external hard drives and computer accessories on Amazon. After winning the trust of thousands of online customers, we’re now expanding offline to bring our best-in-class products even closer to you.',
            'footer_about_us_2' => 'Backed by a 24x7 dedicated support team and loved by users nationwide, Kingster stands for quality, innovation, and unbeatable value.',
            'ig_link' => 'https://www.instagram.com/kingster.india?igsh=MTAycGdyd3Njd2ljcQ%3D%3D&utm_source=qr',
            'wp_link' => 'https://api.whatsapp.com/send?phone=918866513744&text=Hello Kingster Team!!',
            'footer_copyright' => 'Copyright © 2025 Kingster. All Rights Reserved.',
            'active_clients' => 212089,
            'expert_mechanics' => 10,
            'reputation_years' => 7,
            'first_reviewer_name' => 'JAY RAVAL',
            'first_reviewer_msg' => "I really liked this hard drive. The data transfer speed is really great. It connects easily to mobiles because of the Type-C port. The design looks slim and premium. It is the best for storage, and now I don't have to worry about losing data.",
            'second_reviewer_name' => 'VIPUL SHAH',
            'second_reviewer_msg' => 'Buy Kingster hard drive I like that change. We were looking for the product. Easy to install and not too compact to carry around. This is becoming my best partner for all office data.',
            'third_reviewer_name' => 'PARTH DESAI',
            'third_reviewer_msg' => 'Comes with both TYPE-C and USB ports, so equally useful in both phones and laptops. The design is classy and the performance is great!. The design is also attractive. The sturdy design and compatibility with the Type-C port are nice But overall it is value for money',
            'created_by' => 1,
            'modified_by' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);


        DB::table('products')->insert([
            [
                'id' => 1,
                'index' => 1,
                'product_name' => 'External Hard Disk',
                'offer_price' => 1800.00,
                'original_price' => 2000.00,
                'features' => 'Type-C port, 1 x Kingster Ultra Slim External Hard Drive, 1 x High-Speed USB 3.0 Data Cable, 1 x User Guide / Quick Start Manual, 1 x Warranty Card, Protective Bubble Packing (for safe transit)',
                'rating' => 4.9,
                'review_count' => 89,
                'sold_count' => 18590,
                'description' => "=>At Kingster, we are committed to providing premium storage solutions backed by reliable after-sales support. When you purchase a Kingster External Hard Drive, you're not just getting high-speed data storage—you’re gaining peace of mind with our dedicated customer service.\n=>Warranty Period: 1-Year Limited Warranty from the date of purchase.",
                'default_img' => 'uploads/products/hhd_main.jpg',
                'img_1' => 'uploads/products/hhd_1.jpg',
                'img_2' => 'uploads/products/hhd_2.jpg',
                'img_3' => 'uploads/products/hhd_3.jpg',
                'img_4' => 'uploads/products/hhd_4.jpg',
                'img_5' => null,
                'img_6' => null,
                'img_7' => null,
                'img_8' => null,
                'img_9' => null,
                'img_10' => null,
                'is_variant' => 1,
                'variant_1_name' => '320GB',
                'variant_1_price' => 1800.00,
                'variant_1_oprice' => 2000.00,
                'variant_1_offer' => 10,
                'variant_2_name' => '500GB',
                'variant_2_price' => 1900.00,
                'variant_2_oprice' => 2200.00,
                'variant_2_offer' => 13.64,
                'variant_3_name' => '1TB',
                'variant_3_price' => 3000.00,
                'variant_3_oprice' => 5500.00,
                'variant_3_offer' => 45.45,
                'created_by' => 1,
                'modified_by' => 1,
                'status' => 1,
                'is_deleted' => 0,
                'created_at' => Carbon::parse('2025-06-27 22:49:37'),
                'updated_at' => Carbon::parse('2025-06-27 22:54:04'),
            ],
            [
                'id' => 2,
                'index' => 2,
                'product_name' => 'Moniter Display',
                'offer_price' => 4900.00,
                'original_price' => 5400.00,
                'features' => 'Experienced Technicians, Fast & Reliable Support, Affordable Pricing, On-Site & Remote Services Available, Satisfaction Guaranteed',
                'rating' => 4.8,
                'review_count' => 560,
                'sold_count' => 1500,
                'description' => 'We offer complete monitor setup and configuration services, including multi-monitor display arrangements tailored to your workspace. Our team ensures precise display calibration and optimization for accurate color and resolution. We handle monitor troubleshooting and repairs, providing reliable solutions for hardware or display issues. For a clean and professional look, we provide wall-mounting and cable management. We also specialize in corporate display solutions ideal for offices, conference rooms, and presentation spaces.',
                'default_img' => 'uploads/products/display_main.jpg',
                'img_1' => 'uploads/products/display_1.jpg',
                'img_2' => 'uploads/products/display_2.jpg',
                'img_3' => 'uploads/products/display_3.jpg',
                'img_4' => 'uploads/products/display_4.jpg',
                'img_5' => null,
                'img_6' => null,
                'img_7' => null,
                'img_8' => null,
                'img_9' => null,
                'img_10' => null,
                'is_variant' => 1,
                'variant_1_name' => "22'' Inch",
                'variant_1_price' => 4900.00,
                'variant_1_oprice' => 5400.00,
                'variant_1_offer' => 9.26,
                'variant_2_name' => "24'' Inch",
                'variant_2_price' => 6700.00,
                'variant_2_oprice' => 7300.00,
                'variant_2_offer' => 8.22,
                'variant_3_name' => "27'' Inch",
                'variant_3_price' => 7500.00,
                'variant_3_oprice' => 8100.00,
                'variant_3_offer' => 7.41,
                'created_by' => 1,
                'modified_by' => 1,
                'status' => 1,
                'is_deleted' => 0,
                'created_at' => Carbon::parse('2025-06-28 00:20:35'),
                'updated_at' => Carbon::parse('2025-06-28 00:20:35'),
            ],
            [
                'id' => 3,
                'index' => 3,
                'product_name' => 'Flash Drive',
                'offer_price' => 400.00,
                'original_price' => 600.00,
                'features' => 'Fast Data Transfer, Speed Optimization, Secure Solutions, Affordable Services',
                'rating' => 4.7,
                'review_count' => 480,
                'sold_count' => 9800,
                'description' => 'We provide end-to-end USB data transfer and backup services for fast and secure file movement between devices. Our team handles formatting and partitioning to optimize storage usage, and performs speed optimization for enhanced performance. We also offer data security and encryption setup to protect sensitive files with password protection. If you\'re experiencing issues, our error troubleshooting service addresses file corruption, access errors, and more. We ensure full device compatibility checks across PC, Mac, and other systems. Plus, we share expert maintenance and care tips to extend the lifespan and reliability of your flash drives.',
                'default_img' => 'uploads/products/pendrive_main.jpg',
                'img_1' => 'uploads/products/pendrive_1.jpg',
                'img_2' => 'uploads/products/pendrive_2.jpg',
                'img_3' => null,
                'img_4' => null,
                'img_5' => null,
                'img_6' => null,
                'img_7' => null,
                'img_8' => null,
                'img_9' => null,
                'img_10' => null,
                'is_variant' => 1,
                'variant_1_name' => '64GB',
                'variant_1_price' => 400.00,
                'variant_1_oprice' => 600.00,
                'variant_1_offer' => 33.33,
                'variant_2_name' => '128GB',
                'variant_2_price' => 750.00,
                'variant_2_oprice' => 950.00,
                'variant_2_offer' => 21.05,
                'variant_3_name' => '256GB',
                'variant_3_price' => 1400.00,
                'variant_3_oprice' => 2000.00,
                'variant_3_offer' => 30,
                'created_by' => 1,
                'modified_by' => 1,
                'status' => 1,
                'is_deleted' => 0,
                'created_at' => Carbon::parse('2025-06-28 00:25:23'),
                'updated_at' => Carbon::parse('2025-06-28 00:25:23'),
            ],
            [
                'id' => 4,
                'index' => 4,
                'product_name' => '360 Laptop Stand Metal',
                'offer_price' => 750.00,
                'original_price' => 999.00,
                'features' => 'Stand setup & assembly, 360° rotation adjustment, Ergonomic height & angle customization, Cable management tips, Cleaning & maintenance guidance, Compatibility check',
                'rating' => 4.8,
                'review_count' => 150,
                'sold_count' => 8931,
                'description' => 'We offer complete laptop stand setup and assembly, ensuring quick and secure installation for stable support. Our service includes 360° rotation adjustment for smooth and flexible viewing angles, along with ergonomic height and angle customization to minimize neck and back strain. We guide you with effective cable management to keep your workspace tidy and clutter-free. To maintain the look and durability of your stand, we provide essential cleaning and maintenance tips. Additionally, we perform a compatibility check to ensure your laptop\'s size and weight are perfectly supported.',
                'default_img' => 'uploads/products/stand_main.jpg',
                'img_1' => 'uploads/products/stand_1.jpg',
                'img_2' => 'uploads/products/stand_2.jpg',
                'img_3' => 'uploads/products/stand_3.jpg',
                'img_4' => null,
                'img_5' => null,
                'img_6' => null,
                'img_7' => null,
                'img_8' => null,
                'img_9' => null,
                'img_10' => null,
                'is_variant' => 0,
                'variant_1_name' => null,
                'variant_1_price' => null,
                'variant_1_oprice' => null,
                'variant_1_offer' => null,
                'variant_2_name' => null,
                'variant_2_price' => null,
                'variant_2_oprice' => null,
                'variant_2_offer' => null,
                'variant_3_name' => null,
                'variant_3_price' => null,
                'variant_3_oprice' => null,
                'variant_3_offer' => null,
                'created_by' => 1,
                'modified_by' => 1,
                'status' => 1,
                'is_deleted' => 0,
                'created_at' => Carbon::parse('2025-06-28 00:29:42'),
                'updated_at' => Carbon::parse('2025-06-28 00:29:42'),
            ],
            [
                'id' => 5,
                'index' => 5,
                'product_name' => 'Gaming Keyboard',
                'offer_price' => 1500.00,
                'original_price' => 1800.00,
                'features' => 'Wireless keyboard & mouse setup, Key mapping & macro programming, Mouse DPI & sensitivity adjustment, Battery setup & power tips, Wireless lag reduction & signal boost, RGB lighting customization, Compatibility check with devices, Troubleshooting & quick fixes, User guidance & pro tips',
                'rating' => 4.9,
                'review_count' => 1258,
                'sold_count' => 258000,
                'description' => 'We provide full product setup and configuration to ensure your wireless keyboard and mouse combo is properly connected and optimized for peak gaming performance. Our service includes custom key mapping and DPI adjustments, allowing you to tailor controls and sensitivity to suit your play style. Enhance your setup with RGB lighting configuration, personalizing effects, colors, and profiles. We also handle wireless connectivity optimization to reduce lag and ensure a stable, interference-free signal. With thorough compatibility checks, we ensure your gear works seamlessly across PCs, consoles, or other devices. For any issues like lag or disconnections, our troubleshooting and repair service provides fast fixes. Plus, we offer user guidance and after-sales support to help you get the most out of your gaming accessories.',
                'default_img' => 'uploads/products/keyboard_main.jpg',
                'img_1' => 'uploads/products/keyboard_1.jpg',
                'img_2' => 'uploads/products/keyboard_2.jpg',
                'img_3' => 'uploads/products/keyboard_3.jpg',
                'img_4' => null,
                'img_5' => null,
                'img_6' => null,
                'img_7' => null,
                'img_8' => null,
                'img_9' => null,
                'img_10' => null,
                'is_variant' => 0,
                'variant_1_name' => null,
                'variant_1_price' => null,
                'variant_1_oprice' => null,
                'variant_1_offer' => null,
                'variant_2_name' => null,
                'variant_2_price' => null,
                'variant_2_oprice' => null,
                'variant_2_offer' => null,
                'variant_3_name' => null,
                'variant_3_price' => null,
                'variant_3_oprice' => null,
                'variant_3_offer' => null,
                'created_by' => 1,
                'modified_by' => 1,
                'status' => 1,
                'is_deleted' => 0,
                'created_at' => Carbon::parse('2025-06-28 00:34:51'),
                'updated_at' => Carbon::parse('2025-06-28 00:34:51'),
            ],
            [
                'id' => 6,
                'index' => 6,
                'product_name' => 'TWS Earbuds',
                'offer_price' => 999.00,
                'original_price' => 1499.00,
                'features' => 'TWS pairing and setup with devices, audio and mic quality optimization, charging and battery care support, low-latency/gaming mode setup, connectivity and sound issue fixes, cleaning and maintenance guidance, Bluetooth range and stability check, touch control and feature training.',
                'rating' => 4.8,
                'review_count' => 890,
                'sold_count' => 501578,
                'description' => 'We offer complete TWS earbuds setup and support, starting with seamless initial pairing and device syncing across phones, laptops, and other devices. Our experts fine-tune sound and mic quality to ensure clear audio for calls, meetings, and music. We provide guidance on charging practices and battery health to help extend the life of your earbuds and charging case. For gamers, we assist in enabling low-latency or gaming modes for enhanced real-time performance. If you face issues such as one side not working, pairing errors, or sound dropouts, our troubleshooting and repair services have you covered. We also share essential cleaning and maintenance tips to keep your earbuds in top shape. Our Bluetooth range and stability checks help prevent connection drops. Finally, we offer user training to help you master touch controls, voice assistant features, and more hidden functionalities.',
                'default_img' => 'uploads/products/tws_main.jpg',
                'img_1' => 'uploads/products/tws_1.jpg',
                'img_2' => 'uploads/products/tws_2.jpg',
                'img_3' => 'uploads/products/tws_3.jpg',
                'img_4' => null,
                'img_5' => null,
                'img_6' => null,
                'img_7' => null,
                'img_8' => null,
                'img_9' => null,
                'img_10' => null,
                'is_variant' => 0,
                'variant_1_name' => null,
                'variant_1_price' => null,
                'variant_1_oprice' => null,
                'variant_1_offer' => null,
                'variant_2_name' => null,
                'variant_2_price' => null,
                'variant_2_oprice' => null,
                'variant_2_offer' => null,
                'variant_3_name' => null,
                'variant_3_price' => null,
                'variant_3_oprice' => null,
                'variant_3_offer' => null,
                'created_by' => 1,
                'modified_by' => 1,
                'status' => 1,
                'is_deleted' => 0,
                'created_at' => Carbon::parse('2025-06-28 00:36:39'),
                'updated_at' => Carbon::parse('2025-06-28 00:36:39'),
            ],
        ]);
    }
}
